Added support for MongoDB REST Interface
Reformatted the init file, it was a mess

Any changes to the init file will trigger a restart

diff --git a/templates/default/mongodb.init.erb b/templates/default/mongodb.init.erb
--- a/templates/default/mongodb.init.erb
+++ b/templates/default/mongodb.init.erb
@@ -30,20 +30,20 @@
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: An object/document-oriented database
-# Description:       MongoDB is a high-performance, open source, schema-free 
+# Description:       MongoDB is a high-performance, open source, schema-free
 #                    document-oriented  data store that's easy to deploy, manage
 #                    and use. It's network accessible, written in C++ and offers
 #                    the following features:
-#                    
+#
 #                       * Collection oriented storage - easy storage of object-
 #                         style data
 #                       * Full index support, including on inner objects
 #                       * Query profiling
 #                       * Replication and fail-over support
-#                       * Efficient storage of binary data including large 
+#                       * Efficient storage of binary data including large
 #                         objects (e.g. videos)
 #                       * Auto-sharding for cloud-level scalability (Q209)
-#                    
+#
 #                    High performance, scalability, and reasonable depth of
 #                    functionality are the goals for the project.
 ### END INIT INFO
@@ -55,182 +55,178 @@ DESC=database
 # Default defaults.  Can be overridden by the /etc/default/$NAME
 NAME=mongodb
 CONF=<%= @node[:mongodb][:config] %>
+REST=<%= @node[:mongodb][:rest] %>
 PIDFILE=<%= @node[:mongodb][:pidfile] %>
-ENABLE_MONGODB=yes
 
 # Include mongodb defaults if available
 if [ -f /etc/default/$NAME ] ; then
-	. /etc/default/$NAME
+  . /etc/default/$NAME
 fi
 
+# Check for daemon bin
 if test ! -x $DAEMON; then
     echo "Could not find $DAEMON"
     exit 0
 fi
 
-if test "x$ENABLE_MONGODB" != "xyes"; then
-    exit 0
+# This will enable the REST Interface for MongoDB if told so
+if test "x$REST" = "xtrue"; then
+  REST=--rest
+else
+  REST=
 fi
 
 . /lib/lsb/init-functions
 
 STARTTIME=1
-DIETIME=10                   # Time to wait for the server to die, in seconds
-                            # If this value is set too low you might not
-                            # let some servers to die gracefully and
-                            # 'restart' will not work
+DIETIME=10  # Time to wait for the server to die, in seconds
+            # If this value is set too low you might not
+            # let some servers to die gracefully and
+            # 'restart' will not work
 
 DAEMONUSER=${DAEMONUSER:-mongodb}
 
 set -e
 
-
 running_pid() {
 # Check if a given process pid's cmdline matches a given name
-    pid=$1
-    name=$2
-    [ -z "$pid" ] && return 1
-    [ ! -d /proc/$pid ] &&  return 1
-    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
-    # Is this the expected server
-    [ "$cmd" != "$name" ] &&  return 1
-    return 0
+  pid=$1
+  name=$2
+  [ -z "$pid" ] && return 1
+  [ ! -d /proc/$pid ] &&  return 1
+  cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
+  # Is this the expected server
+  [ "$cmd" != "$name" ] &&  return 1
+  return 0
 }
 
 running() {
 # Check if the process is running looking at /proc
 # (works for all users)
-
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
-    pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
-    return 0
+  # No pidfile, probably no daemon present
+  [ ! -f "$PIDFILE" ] && return 1
+  pid=`cat $PIDFILE`
+  running_pid $pid $DAEMON || return 1
+  return 0
 }
 
 start_server() {
 # Start the process using the wrapper
-            start-stop-daemon --background --start --quiet --pidfile $PIDFILE \
-                        --make-pidfile --chuid $DAEMONUSER \
-                        --exec $DAEMON -- --config $CONF
-            errcode=$?
-	return $errcode
+  start-stop-daemon --background --start --quiet --pidfile $PIDFILE --make-pidfile --chuid $DAEMONUSER --exec $DAEMON -- $REST --config $CONF
+  errcode=$?
+  return $errcode
 }
 
 stop_server() {
 # Stop the process using the wrapper
-            start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-                        --user $DAEMONUSER \
-                        --exec $DAEMON
-            errcode=$?
-	return $errcode
+  start-stop-daemon --stop --quiet --pidfile $PIDFILE --user $DAEMONUSER --exec $DAEMON
+  errcode=$?
+  return $errcode
 }
 
 force_stop() {
 # Force the process to die killing it manually
-	[ ! -e "$PIDFILE" ] && return
-	if running ; then
-		kill -15 $pid
-	# Is it really dead?
-		sleep "$DIETIME"s
-		if running ; then
-			kill -9 $pid
-			sleep "$DIETIME"s
-			if running ; then
-				echo "Cannot kill $NAME (pid=$pid)!"
-				exit 1
-			fi
-		fi
-	fi
-	rm -f $PIDFILE
+  [ ! -e "$PIDFILE" ] && return
+  if running ; then
+    kill -15 $pid
+    # Is it really dead?
+    sleep "$DIETIME"s
+    if running ; then
+      kill -9 $pid
+      sleep "$DIETIME"s
+      if running ; then
+        echo "Cannot kill $NAME (pid=$pid)!"
+        exit 1
+      fi
+    fi
+  fi
+  rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC" "$NAME"
-        # Check if it's running first
-        if running ;  then
-            log_progress_msg "apparently already running"
-            log_end_msg 0
-            exit 0
-        fi
-        if start_server ; then
-            # NOTE: Some servers might die some time after they start,
-            # this code will detect this issue if STARTTIME is set
-            # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
-            if  running ;  then
-                # It's ok, the server started and is running
-                log_end_msg 0
-            else
-                # It is not running after we did start
-                log_end_msg 1
-            fi
-        else
-            # Either we could not start it
-            log_end_msg 1
-        fi
-	;;
+    log_daemon_msg "Starting $DESC" "$NAME"
+    # Check if it's running first
+    if running ;  then
+      log_progress_msg "apparently already running"
+      log_end_msg 0
+      exit 0
+    fi
+    if start_server ; then
+      # NOTE: Some servers might die some time after they start,
+      # this code will detect this issue if STARTTIME is set
+      # to a reasonable value
+      [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
+      if  running ;  then
+        # It's ok, the server started and is running
+        log_end_msg 0
+      else
+        # It is not running after we did start
+        log_end_msg 1
+      fi
+    else
+      # Either we could not start it
+      log_end_msg 1
+    fi
+  ;;
   stop)
-        log_daemon_msg "Stopping $DESC" "$NAME"
-        if running ; then
-            # Only stop the server if we see it running
-			errcode=0
-            stop_server || errcode=$?
-            log_end_msg $errcode
-        else
-            # If it's not running don't do anything
-            log_progress_msg "apparently not running"
-            log_end_msg 0
-            exit 0
-        fi
-        ;;
+    log_daemon_msg "Stopping $DESC" "$NAME"
+    if running ; then
+      # Only stop the server if we see it running
+      errcode=0
+      stop_server || errcode=$?
+      log_end_msg $errcode
+    else
+      # If it's not running don't do anything
+      log_progress_msg "apparently not running"
+      log_end_msg 0
+      exit 0
+    fi
+  ;;
   force-stop)
-        # First try to stop gracefully the program
-        $0 stop
-        if running; then
-            # If it's still running try to kill it more forcefully
-            log_daemon_msg "Stopping (force) $DESC" "$NAME"
-			errcode=0
-            force_stop || errcode=$?
-            log_end_msg $errcode
-        fi
-	;;
+    # First try to stop gracefully the program
+    $0 stop
+    if running; then
+      # If it's still running try to kill it more forcefully
+      log_daemon_msg "Stopping (force) $DESC" "$NAME"
+      errcode=0
+      force_stop || errcode=$?
+      log_end_msg $errcode
+    fi
+  ;;
   restart|force-reload)
-        log_daemon_msg "Restarting $DESC" "$NAME"
-		errcode=0
-        stop_server || errcode=$?
-        # Wait some sensible amount, some server need this
-        [ -n "$DIETIME" ] && sleep $DIETIME
-        start_server || errcode=$?
-        [ -n "$STARTTIME" ] && sleep $STARTTIME
-        running || errcode=$?
-        log_end_msg $errcode
-	;;
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    errcode=0
+    stop_server || errcode=$?
+    # Wait some sensible amount, some server need this
+    [ -n "$DIETIME" ] && sleep $DIETIME
+    start_server || errcode=$?
+    [ -n "$STARTTIME" ] && sleep $STARTTIME
+    running || errcode=$?
+    log_end_msg $errcode
+  ;;
   status)
-
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if running ;  then
-            log_progress_msg "running"
-            log_end_msg 0
-        else
-            log_progress_msg "apparently not running"
-            log_end_msg 1
-            exit 1
-        fi
-        ;;
+    log_daemon_msg "Checking status of $DESC" "$NAME"
+    if running ;  then
+      log_progress_msg "running"
+      log_end_msg 0
+    else
+      log_progress_msg "apparently not running"
+      log_end_msg 1
+      exit 1
+    fi
+  ;;
   # MongoDB can't reload its configuration.
   reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
-        ;;
-
+    log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
+    log_warning_msg "cannot re-read the config file (use restart)."
+  ;;
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+    N=/etc/init.d/$NAME
+    echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+    exit 1
+  ;;
 esac
 
 exit 0
